spring.application.name=carear-document-BE

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=jean971013568@gmail.com
spring.mail.password=nhsjtznobmzwwafq
spring.mail.to=jean971013568@gmail.com

spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory


opensearch.protocol=https
opensearch.host=localhost
opensearch.port=9200
opensearch.username=admin
opensearch.password=Clush13568!
